first_project/addresses/urls.py
from django.urls import path
from .views import GetAddress, CreateAddress

app_name='addresses'
urlpatterns = [
    path('<int:id>/', GetAddress, name='detail'),
    path('create/', CreateAddress.as_view(), name='create')
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from movies import urls as movies_urls
from users import urls as users_urls
from addresses import urls as address_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include(movies_urls, namespace='movies')),
    path('users/', include(users_urls, namespace='users')),
    path('addresses/', include(address_urls, namespace='addresses'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first_project/users/urls.py
from django.urls import path
from .views import GetUsers, GetUser, CreateUser, UpdateUser, DeleteUser

app_name='users'
urlpatterns = [
    path('', GetUsers, name='list'),
    path('<int:id>/', GetUser, name='detail'),
    path('create/', CreateUser.as_view(), name='create'),
    path('update/<int:id>/', UpdateUser.as_view(), name='update'),
    path('delete/<int:id>/', DeleteUser, name='delete')
]

first_project/addresses/models.py
from django.db import models
from django.contrib.auth.models import User

class Address(models.Model):
    user = models.ForeignKey(User, related_name='addresses', on_delete=models.CASCADE)
    street = models.CharField(max_length=140)
    exterior_number = models.PositiveIntegerField()
    internal_number = models.PositiveIntegerField(blank=True, null=True)
    colony = models.CharField(max_length=100)
    city = models.CharField(max_length=140)
    state = models.CharField(max_length=140)
    country = models.CharField(max_length=140)
    postal_code = models.CharField(max_length=6)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Dirección #{self.id} del usuario {self.user.first_name} {self.user.last_name}'

first_project/addresses/forms.py
from django import forms
from .models import Address

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = '__all__'

first_project/addresses/views.py
from django.shortcuts import render, redirect
from django import views
from .models import Address
from .forms import AddressForm

def GetAddress(request, id):
    address = Address.objects.get(pk=id)
    template_name = 'addresses/detail.html'
    context = {
        'address': address
    }
    return render(request, template_name, context)

class CreateAddress(views.View):
    def get(self, request):
        form = AddressForm()
        template_name = 'addresses/form.html'
        context = {
            'form':form
        }
        return render(request, template_name, context)

    def post(self, request):
        new_form = AddressForm(request.POST) #Recibe la info desde la web
        if new_form.is_valid():
            new_address = new_form.save()
            return redirect('users:list')
        else:
            template_name = 'addresses/form.html'
            context = {
                'form': new_form
            }
            return render(request, template_name, context)

first_project/addresses/templates/addresses/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Dirección perteneciente al usuario:</h1>
    <a href="{% url 'users:detail' address.user.id %}">
        <h1>{{ address.user.first_name }} {{ address.user.last_name }}</h1>
    </a>
    <p>Calle: <b>{{ address.street }}</b></p>
    <p>No. exterior: <b>{{ address.exterior_number }}</b></p>
    {% if address.internal_number %}
        <p>No. interior: <b>{{ address.interal_number }}</b></p>
    {% else %}
        <p>No. interior: N/A</b></p>
    {% endif %}
    <p>Colonia: <b>{{ address.colony }}</b></p>
    <p>Ciudad: <b>{{ address.city }}</b></p>
    <p>Estado: <b>{{ address.state }}</b></p>
    <p>País: <b>{{ address.coutry }}</b></p>
    <p>Código Postal: <b>{{ address.postal_code }}</b></p>
{% endblock content %}       

first_project/addresses/templates/addresses/form.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'addresses:create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Crear dirección">
    </form>
{% endblock content %}