first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from movies import urls as movies_urls
from users import urls as users_urls
from addresses import urls as address_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include(movies_urls, namespace='movies')),
    path('users/', include(users_urls, namespace='users')),
    path('addresses/', include(address_urls, namespace='addresses'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first_project/users/urls.py
from django.urls import path
from .views import GetUsers, GetUser, CreateUser, UpdateUser, DeleteUser

app_name='users'
urlpatterns = [
    path('', GetUsers, name='list'),
    path('<int:id>/', GetUser, name='detail'),
    path('create/', CreateUser.as_view(), name='create'),
    path('update/<int:id>/', UpdateUser.as_view(), name='update'),
    path('delete/<int:id>/', DeleteUser, name='delete')
]

first_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movies django app</title>
</head>
<body>
    <ul>
        <a href="{% url 'movies:list' %}"><li>Ver películas</li></a>
        <a href="{% url 'movies:create' %}"><li>Crear película</li></a>
        <a href="{% url 'users:list' %}"><li>Lista de usuarios</li></a>
        <a href="{% url 'users:create' %}"><li>Crear usuario</li></a>
    </ul>
    {% block content %}
    {% endblock content %}    

    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <p style="color:red">{{ message }}</p>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                <p style="color:yellow">{{ message }}</p>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <p style="color:green">{{ message }}</p>
            {% endif %}
        {% endfor %}
    {% endif %}

    <footer>Actosoft 2020</footer>
</body>
</html>