first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from movies import urls as movies_urls
from users import urls as users_urls
from addresses import urls as address_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include(movies_urls, namespace='movies')),
    path('users/', include(users_urls, namespace='users')),
    path('addresses/', include(address_urls, namespace='addresses'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first_project/users/urls.py
from django.urls import path
from .views import GetUsers, GetUser, CreateUser, UpdateUser, DeleteUser

app_name='users'
urlpatterns = [
    path('', GetUsers, name='list'),
    path('<int:id>/', GetUser, name='detail'),
    path('create/', CreateUser.as_view(), name='create'),
    path('update/<int:id>/', UpdateUser.as_view(), name='update'),
    path('delete/<int:id>/', DeleteUser, name='delete')
]

first_project/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    gender = models.CharField(max_length=140)
    phone = models.CharField(max_length=15)
    age = models.PositiveIntegerField()
    image = models.ImageField(upload_to='images/profile_images/', blank=True, null=True)

    def __str__(self):
        return f'Perfil del usuario {self.user.first_name} {self.user.last_name}'
#profile = Profile.objects.get(pk=1)
#profile.gender 
#profile.phone  
#profile.user.first_name

#user = User.objects.get(id=1)
#user.first_name
#user.profile.age

first_project/users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',
        'email', 'is_active', 'is_staff', 'is_superuser',
        'password']

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',
        'email', 'is_active', 'is_staff', 'is_superuser']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']

first_project/users/views.py
from django.shortcuts import render, redirect
from django import views
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import UserCreateForm, UserUpdateForm, ProfileForm

def GetUsers(request):
    users = User.objects.filter(is_superuser=False)
    template_name = "users/list.html"
    context = {
        'users': users
    }
    return render(request, template_name, context)

def GetUser(request, id):
    user = User.objects.get(id=id)
    template_name = "users/detail.html"
    context = {
        'user': user
    }
    return render(request, template_name, context)

class CreateUser(views.View):
    def get(self, request):
        user_form = UserCreateForm()
        profile_form = ProfileForm()
        template_name = 'users/form.html'
        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }
        return render(request, template_name, context)
    def post(self, request):
        user_form = UserCreateForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(request.POST['password'])
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            messages.success(request, 'Usuario creado con éxito')
            return redirect('users:detail', user.id)
        else:
            template_name = 'users/form.html'
            context = {
                'user_form': user_form,
                'profile_form': profile_form
            }
            messages.error(request, 'Algo falló al crear el usuario')
            return render(request, template_name, context)

class UpdateUser(views.View):
    def get(self, request, id):
        user = User.objects.get(pk=id)
        user_form = UserUpdateForm(instance=user)
        profile_form = ProfileForm(instance=user.profile)
        template_name = 'users/form.html'
        context = {
            'user_form': user_form,
            'profile_form': profile_form,
            'id': id,
            'image': user.profile.image
        }
        return render(request, template_name, context)

    def post(self, request, id):
        user = User.objects.get(pk=id)
        user_form = UserUpdateForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save()
            messages.success(request, 'Usuario actualizado con éxito')
            return redirect('users:detail', user.id)
        else:
            template_name = 'users/form.html'
            context = {
                'user_form': user_form,
                'profile_form': profile_form,
                'id': id,
                'image': user.profile.image
            }
            messages.error(request, 'No se pudo actualizar el usuario')
            return render(request, template_name, context)

def DeleteUser(request, id):
    user = User.objects.get(pk=id)
    user.delete()
    messages.info(request, 'Usuario eliminado')
    return redirect('users:list')

first_project/users/templates/users/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Usuario: {{ user.first_name }} {{ user.last_name }}</h1>
    {% if user.profile.image %}
        <img
        src="{{ user.profile.image.url }}"
        alt="Imagen del usuario" width="50" height="50">
    {% else %}
        <img src="https://cdnlrv.lavoz.com.ar/img/user/default.jpg"
        alt="Imagen default" width="50" height="50">
    {% endif %}
    <p>Email: <b>{{ user.email }}</b></p>
    <p>Nombre de usuario: <b>{{ user.username }}</b></p>
    <p>Género: <b>{{ user.profile.gender }}</b></p>
    <p>Edad: <b>{{ user.profile.age }}</b></p>
    <p>Teléfono: <b>{{ user.profile.phone }}</b></p>
    <h2>Direcciones del usuario</h2>
    {% if user.addresses.all|length > 0 %}
        {% for address in user.addresses.all %}
            <a href="{% url 'addresses:detail' address.id %}">
                <p>{{ address.street }}, {{ address.city }} - {{address.postal_code}}</p>
            </a>
        {% endfor %}
    {% else %}
        <h3>Ups! Aún no cuentas con direcciones registradas</h3>
    {% endif %}
    <a href="{% url 'users:update' user.id %}"><button>Editar usuario</button></a>
    <a href="{% url 'users:delete' user.id %}"><button>Eliminar usuario</button></a>
{% endblock content %}

first_project/users/templates/users/form.html
{% extends 'base.html' %}

{% block content %}
    {% if id %}
        <h1>Editar usuario</h1>
        <form action="{% url 'users:update' id %}" method="POST"
            enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            {% if image %}
                <img src="{{ image.url }}" alt="Imagen"
                width="100" heigth="100">
            {% else %}
                <img src="https://cdnlrv.lavoz.com.ar/img/user/default.jpg"
                alt="Imagen default" width="50" height="50">
            {% endif %}
            <input type="submit" value="Guardar cambios">
    {% else %}
        <h1>Crea un nuevo usuario</h1>
        <form action="{% url 'users:create' %}" method="POST"
            enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Crear usuario">
        </form>
    {% endif %}
{% endblock content %}

first_project/users/templates/users/list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Lista de usuarios</h1>
    {% for user in users %}
        <a href="{% url 'users:detail' user.id %}"><p>{{ user.first_name }} {{ user.last_name }}</p></a>
    {% endfor %}
{% endblock content %}