first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from movies import urls as movies_urls
from users import urls as users_urls
from addresses import urls as address_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include(movies_urls, namespace='movies')),
    path('users/', include(users_urls, namespace='users')),
    path('addresses/', include(address_urls, namespace='addresses'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first_project/movies/urls.py
from django.urls import path
from .views import GetMovies, GetMovie, CreateMovie, CreateMovieEasy, UpdateMovie, DeleteMovie

app_name='movies'
urlpatterns = [
    #path('movies/', GetMovies)
    path('', GetMovies, name='list'), #está entrando a la view getmovies
    path('<int:id>/', GetMovie, name='detail'),
    #path('create/', CreateMovie.as_view())
    path('create/', CreateMovieEasy.as_view(), name='create'),
    path('update/<int:id>/', UpdateMovie.as_view(), name='update'),
    path('delete/<int:id>/', DeleteMovie, name='delete')
]

first_project/users/urls.py
from django.urls import path
from .views import GetUsers, GetUser, CreateUser, UpdateUser, DeleteUser

app_name='users'
urlpatterns = [
    path('', GetUsers, name='list'),
    path('<int:id>/', GetUser, name='detail'),
    path('create/', CreateUser.as_view(), name='create'),
    path('update/<int:id>/', UpdateUser.as_view(), name='update'),
    path('delete/<int:id>/', DeleteUser, name='delete')
]

first_project/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model): #Siempre hay que heredar de models.Model
    title = models.CharField(max_length=140)
    sinopsis = models.TextField(blank=True, null=True)
    duration = models.PositiveIntegerField()
    calif = models.PositiveIntegerField(default=5)
    gender = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
        

class Actor(models.Model):
    name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    experience_years = models.PositiveIntegerField()
    awards = models.PositiveIntegerField()
    biography = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True)       

    def __str__(self):
        return self.name + ' ' + self.last_name

first_project/movies/forms.py
from django import forms 
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie 
        fields = '__all__'
        

first_project/movies/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django import views
from .models import Movie
from .forms import MovieForm

#Hay dos formas de crear vistas
#1.- creando una clase
#2.- creando una función

# Create your views here.

def GetMovies(request):
    #vamos a traer todas las peliculas
    movies = Movie.objects.all() #equivalente al select * from movies_movie
    #print(movies)
    #return HttpResponse('Funciona!')
    template_name = 'movies/list.html'
    context = {
        'movies': movies
    }
    return render(request, template_name, context)

def GetMovie(request, id):
    movie = Movie.objects.get(pk=id)
    template_name = 'movies/detail.html'
    context = {
        'movie': movie
    }
    return render(request, template_name, context)

class CreateMovie(views.View):
    def get(self, request):
        template_name = 'movies/form.html'
        return render(request, template_name)

    def post(self, request):
        data = request.POST
        #print(data)       
        new_movie = Movie.objects.create(
            title=data['title'],
            sinopsis=data['sinopsis'],
            duration=data['duration'],
            calif=data['calif'],
            gender=data['gender']
        )  
        if new_movie:
            print('Película creada con éxito!')
            return redirect('/movies/')
        else:
            print('La película no se pudo crear...')
            return redirect('/movies/create/')    


class CreateMovieEasy(views.View):
    def get(self, request):
        form = MovieForm()
        template_name = 'movies/form_easy.html'
        context = {
            'form': form
        }
        return render(request, template_name, context)
    def post(self, request):
        new_form = MovieForm(request.POST)
        if new_form.is_valid():
            new_movie = new_form.save()
            print('Se creó la película correctamente', new_movie)
            return redirect('movies:list')
        else:
            template_name = 'movies/form_easy.html'
            context = {
                'form': new_form
            }
            return render(request, template_name, context)


class UpdateMovie(views.View):
    def get(self, request, id):
        movie = Movie.objects.get(pk=id)
        form = MovieForm(instance=movie)
        template_name = 'movies/form_easy.html'
        context = {
            'form': form,
            'id': id
        }
        return render(request, template_name, context)
    def post(self, request, id):
        movie = Movie.objects.get(pk=id)
        update_form = MovieForm(request.POST, instance=movie)
        if update_form.is_valid():
            form_updated = update_form.save()
            return redirect('movies:detail', id)
        else:
            template_name = 'movies/form_easy.html'
            context = {
                'form': update_form,
                'id': id
            }
            return render(request, template_name, context)
def DeleteMovie(request, id):
    movie = Movie.objects.get(pk=id)
    movie.delete()
    return redirect('movies:detail')

first_project/movies/templates/movies/detail.html
{% extends 'base.html'%}

{% block content %}
    <h1>Detalle de la pelicula # {{ movie.id }}</h1>
    <h3>Titulo: {{ movie.title }}</h3>
    <p>Sinopsis: </p>
    <p>{{ movie.sinopsis }}</p>
    <p>Duracion: {{ movie.duration }}</p>
    <a href="{% url 'movies:update' movie.id %}"><button>Editar película</button></a>
    <a href="{% url 'movies:delete' movie.id %}"><button>Eliminar película</button></a>

{% endblock content%}

first_project/movies/templates/movies/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Película</title>
</head>
<body>
    <form action="/movies/create/" method="POST">
        {% csrf_token %}
        <label for="title">Ingresa el título</label>
        <input type="text" name="title" id="title" placeholder="Titulo">
        <label for="sinopsis">Ingresa la sinopsis</label>
        <textarea name="sinopsis" id="sinopsis" cols="30" rows="10"></textarea>
        <label for="duration">Ingresa la duración en minutos</label>
        <input type="number" name="duration" id="duration" placeholder="100 min.">
        <label for="calif">Ingresa la calificación (1 al 5)</label>
        <input type="number" name="calif" id="calif" placeholder="5">
        <label for="gender">Ingresa tu género</label>
        <input type="text" name="gender" id="gender" placeholder="Acción">
        <input type="submit" value="Crear película">
    </form>
</body>
</html>

first_project/movies/templates/movies/form_easy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="
        {% if id %}
            {% url 'movies:update' id %}
        {%else%}
            {% url 'movies:create' %}
        {% endif %}
    " method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="
            {% if id %} Actualizar {% else %} Crear película {% endif %}
        ">
    </form>    
</body>
</html>

first_project/movies/templates/movies/list.html
<!DOCTYPE html>
{% extends 'base.html'%}

{% block content %}
    <h1>Lista de peliculas disponibles</h1>
    <ul>
        {% for movie in movies %}
            <a href="{% url 'movies:detail' movie.id %}"><li>{{ movie.title }}</li></a>
        {% endfor %}
    </ul>
{% endblock content %}   